query CartInput {
  presentmentCurrencyRate
  cart {
    lines {
      id
      quantity
      offer: attribute(key: "_oo_offer") {
        value
      }
      bundle: attribute(key: "_oo_bundle") {
        value
      }
      gift: attribute(key: "_oo_gift") {
        value
      }
      cost {
        amountPerQuantity {
          amount
        }
      }
      merchandise {
        __typename
        ... on ProductVariant {
          product {
            id
          }
        }
      }
    }
  }
  discount {
    discountClasses
    metafield(namespace: "$app", key: "offers") {
      jsonValue
    }
  }
}
