query DeliveryInput {
  presentmentCurrencyRate
  cart {
    cost {
      subtotalAmount {
        amount
      }
    }
    lines {
      quantity
      offer: attribute(key: "_oo_offer") {
        value
      }
      gift: attribute(key: "_oo_gift") {
        value
      }
      cost {
        amountPerQuantity {
          amount
        }
      }
    }
    deliveryGroups {
      id
    }
  }
  discount {
    discountClasses
    metafield(namespace: "$app", key: "offers") {
      jsonValue
    }
  }
}
