<?php

/*
|--------------------------------------------------------------------------
| Public feature pages
|--------------------------------------------------------------------------
|
| Copy from the Combined MVP Scope, Part E1/E2 (page copy), section 6
| (keywords) and section 11 (SEO titles). Metrics are illustrative and are
| labelled as such on the page.
|
*/

return [

    'bundles' => [
        'group' => 'convert',
        'name' => 'Bundles',
        'menu' => 'Mix & match, tiered and gift-box bundles',
        'icon' => 'bundle',
        'eyebrow' => 'SHOPIFY BUNDLES',
        'h1' => 'Build bundles shoppers actually complete.',
        'hero' => 'Mix & match, tiered, routine and gift-box bundles that add to cart the Shopify way — no theme code, no cart hacks.',
        'secondary_cta' => ['label' => 'Browse Bundle Templates', 'href' => '/templates?type=bundle'],
        'seo_title' => 'Shopify Bundle App | OrderOrbit',
        'seo_description' => 'Create mix & match, tiered and gift-box bundles on Shopify with native cart support and built-in analytics.',
        'keyword' => 'Shopify bundle app',
        'problem' => ['Bundles shouldn\'t break your store.', 'Most bundle apps rewrite your cart, fight your theme or confuse shoppers with clunky pickers. The result: abandoned selections and support tickets.'],
        'steps_heading' => 'Live in four steps.',
        'steps' => ['Choose a bundle type.', 'Pick products and rules.', 'Style it to match your brand.', 'Place it in the Theme Editor and publish.'],
        'grid' => ['Six bundle templates', 'Required and optional items', 'Min/max selection rules', 'Fixed, percentage or tiered savings', 'Gift item and progress indicator', 'Subscription-aware where supported', 'Mobile-first design', 'Built-in view, selection and completion tracking'],
        'example' => ['title' => 'The skincare routine.', 'text' => 'Cleanser (required) + choose 2 of 4 serums + moisturiser → save 15%, with a progress bar showing "1 more to unlock your saving".', 'flow' => ['Cleanser (required)', 'Choose 2 of 4 serums', 'Moisturiser', 'Save 15%']],
        'templates' => ['Premium Bundle', 'Mix & Match', 'Tiered / Buy More Save More', 'Routine Builder', 'Gift Box', 'Visual Product Bundle'],
        'metrics' => [['Bundle views', '12,480'], ['Selections', '4,102'], ['Completions', '1,318'], ['Bundle revenue', '$58,940']],
        'faqs' => [
            ['Does it work with my theme?', 'Yes, it\'s a Theme App Block you place in the Theme Editor.'],
            ['Do bundles use real Shopify products?', 'Yes; inventory, variants and prices come from Shopify.'],
            ['Can I A/B test bundle designs?', 'Yes, on the Growth plan and above.'],
        ],
    ],

    'free-gift' => [
        'group' => 'convert',
        'name' => 'Free Gift',
        'menu' => 'Spend thresholds that unlock a gift',
        'icon' => 'gift',
        'eyebrow' => 'GIFT WITH PURCHASE',
        'h1' => 'Reward bigger carts with a free gift.',
        'hero' => 'Set one or more spend thresholds, show live progress and let shoppers unlock a gift they can see.',
        'seo_title' => 'Shopify Free Gift with Purchase App | OrderOrbit',
        'seo_description' => 'Single or multi-threshold gift-with-purchase campaigns with live progress and unlock states for Shopify.',
        'keyword' => 'Shopify free gift with purchase',
        'problem' => ['A gift nobody sees doesn\'t lift AOV.', 'Hidden promo codes and fine print don\'t change behaviour. Shoppers need to see how close they are.'],
        'steps' => ['Set your threshold(s).', 'Choose the gift product.', 'Pick a progress, ladder or reveal template.', 'Place and publish.'],
        'grid' => ['Single or multi-threshold campaigns', 'Reward ladder', 'Progress, unlocked and claimed states', 'Eligibility by product, collection or customer', 'Custom messages', 'Unlock and claim tracking'],
        'example' => ['title' => 'A two-step reward ladder.', 'text' => 'Spend $50 → free sample kit; spend $100 → free full-size product.', 'flow' => ['Cart $0', 'Spend $50', 'Free sample kit', 'Spend $100', 'Free full-size product']],
        'templates' => ['Minimal', 'Progress Card', 'Reward Ladder', 'Premium Gift Card', 'Product Reveal', 'Compact Cart Bar'],
        'metrics' => [['Gift views', '18,204'], ['Unlocked', '3,960'], ['Claimed', '3,412'], ['AOV lift', '+$14.20']],
        'faqs' => [
            ['Is the gift added automatically?', 'You choose auto-add or claim.'],
            ['What if the gift sells out?', 'The campaign shows a fallback message and stops offering it.'],
            ['Does it work in multiple currencies?', 'Thresholds convert with Shopify Markets.'],
        ],
    ],

    'free-shipping-bar' => [
        'group' => 'convert',
        'name' => 'Free Shipping Bar',
        'menu' => 'Progress toward free shipping',
        'icon' => 'truck',
        'eyebrow' => 'SHIPPING PROGRESS',
        'h1' => 'Show shoppers how close they are to free shipping.',
        'hero' => 'A shipping progress bar you place anywhere the Theme Editor allows, with rewards at one or more thresholds.',
        'seo_title' => 'Shopify Free Shipping Bar | OrderOrbit',
        'seo_description' => 'A shipping progress bar you place anywhere in the Theme Editor, with multi-threshold rewards and tracking.',
        'keyword' => 'Shopify free shipping bar',
        'problem' => ['"Free shipping over $X" only works if people notice it.', 'A static banner is easy to ignore. A bar that moves with the cart gives shoppers a reason to add one more item.'],
        'steps' => ['Set threshold(s).', 'Choose the reward.', 'Write your messages.', 'Place the block and publish.'],
        'grid' => ['Four templates', 'Multi-threshold reward ladder', 'Free shipping, gift or discount rewards', 'Remaining-amount message', 'Multi-currency', 'Threshold-reached tracking'],
        'example' => ['title' => 'A bar that moves with the cart.', 'text' => '"You\'re $12 away from free shipping" → "You\'ve unlocked free shipping!"', 'flow' => ['Cart $48', '$12 away', 'Add one more item', 'Free shipping unlocked']],
        'templates' => ['Minimal', 'Progress', 'Reward Ladder', 'Premium Card'],
        'metrics' => [['Bar views', '41,730'], ['Threshold reached', '6,284'], ['Orders over threshold', '38%'], ['AOV lift', '+$9.60']],
        'faqs' => [
            ['Where can I place it?', 'Anywhere your theme supports app blocks: header area, product page, cart.'],
            ['Does it apply the shipping discount?', 'The bar displays progress; the free-shipping rule itself is your Shopify shipping or discount setting.'],
        ],
    ],

    'quantity-breaks' => [
        'group' => 'convert',
        'name' => 'Quantity Breaks',
        'menu' => 'Buy more, save more tiers',
        'icon' => 'layers',
        'eyebrow' => 'VOLUME DISCOUNTS',
        'h1' => 'Sell more units with quantity discounts.',
        'hero' => 'Tier cards and pricing tables that make "buy more, save more" obvious at a glance.',
        'seo_title' => 'Shopify Quantity Breaks & Volume Discounts | OrderOrbit',
        'seo_description' => 'Tier cards and pricing tables that make buy more, save more obvious on Shopify product pages.',
        'keyword' => 'Shopify quantity breaks',
        'problem' => ['Shoppers won\'t calculate savings for you.', 'If the per-unit saving isn\'t clear, most people buy one.'],
        'steps' => ['Add quantity tiers.', 'Set price or saving per tier.', 'Pick a layout and default tier.', 'Publish on your product pages.'],
        'grid' => ['Five layouts', 'Per-unit or total pricing', 'Percentage or amount savings', 'Default and Most Popular tier', 'Product/variant targeting', 'Native cart quantity'],
        'example' => ['title' => 'Three clear tiers.', 'text' => 'Buy 1 $29 • Buy 2 $26 each • Buy 3 $23 each — Most Popular.', 'flow' => ['Buy 1 · $29', 'Buy 2 · $26 each', 'Buy 3 · $23 each ★']],
        'templates' => ['Tier Cards', 'Radio Selector', 'Horizontal Tiers', 'Premium Pricing Table', 'Compact Selector'],
        'metrics' => [['Tier views', '22,915'], ['Multi-unit orders', '2,847'], ['Units per order', '2.3'], ['Revenue', '$71,380']],
        'faqs' => [
            ['Does it change my prices?', 'Savings apply through Shopify-compatible discounts.'],
            ['Can I limit it to some products?', 'Yes, by product or variant.'],
        ],
    ],

    'upsell-cross-sell' => [
        'group' => 'convert',
        'name' => 'Upsell & Cross-sell',
        'menu' => 'Product-page and cart recommendations',
        'icon' => 'sparkle',
        'eyebrow' => 'UPSELLS',
        'h1' => 'Recommend the next product at the right moment.',
        'hero' => 'Product-page and cart upsells with targeting, incentives and accept/decline tracking.',
        'seo_title' => 'Shopify Upsell & Cross-sell App | OrderOrbit',
        'seo_description' => 'Add product-page and cart upsells with targeting, incentives and revenue tracking.',
        'keyword' => 'Shopify upsell app',
        'problem' => ['Pop-ups interrupt. Good upsells help.', 'Forced drawers and surprise modals hurt trust. Recommendations placed where shoppers are already deciding feel natural.'],
        'steps' => ['Choose product page or cart.', 'Set the recommendation and rules.', 'Add an optional incentive.', 'Place and publish.'],
        'grid' => ['Product page block', 'Cart and cart-drawer block (cart-page fallback)', 'Product, collection, cart-value and customer rules', 'Incentive display', 'Accept/decline tracking', 'Never force-opens your drawer'],
        'example' => ['title' => 'The camera accessory.', 'text' => 'Viewing a camera → "Add a 64GB memory card and save 10%".', 'flow' => ['Viewing a camera', 'Recommend 64GB card', 'Save 10%', 'Added to cart']],
        'templates' => ['Product Card', 'Side-by-Side', 'Compact', 'Premium Offer', 'Cart Carousel', 'Cart Grid', 'Cart Horizontal', 'Cart Minimal Card'],
        'metrics' => [['Upsell views', '30,112'], ['Accepted', '2,409'], ['Accept rate', '8.0%'], ['Upsell revenue', '$36,150']],
        'faqs' => [
            ['Does it work with my cart drawer?', 'Where your theme supports a drawer app block; otherwise it shows on the cart page.'],
            ['Can I target returning customers?', 'Yes, with segments.'],
        ],
    ],

    'countdown-timer' => [
        'group' => 'convert',
        'name' => 'Countdown Timer',
        'menu' => 'Real deadlines for real campaigns',
        'icon' => 'clock',
        'eyebrow' => 'CAMPAIGN TIMERS',
        'h1' => 'Add real deadlines to real campaigns.',
        'hero' => 'Countdown banners and product timers tied to genuine campaign end dates.',
        'seo_title' => 'Shopify Countdown Timer | OrderOrbit',
        'seo_description' => 'Countdown banners and product timers tied to genuine campaign end dates for Shopify stores.',
        'keyword' => 'Shopify countdown timer',
        'problem' => ['Fake urgency costs trust.', 'Timers that reset on refresh are noticed. OrderOrbit timers count down to a real end date you set.'],
        'steps' => ['Set the end date and timezone.', 'Pick a template.', 'Target products or collections.', 'Publish.'],
        'grid' => ['Five templates', 'Timezone-aware', 'Product and collection targeting', 'Auto-hide or ended message', 'View and click tracking'],
        'example' => ['title' => 'A genuine sale deadline.', 'text' => '"Summer Sale ends in 02d 14h 09m".', 'flow' => ['Set end date', 'Timer counts down', 'Sale ends', 'Timer hides']],
        'templates' => ['Minimal', 'Banner', 'Premium Card', 'Offer Countdown', 'Product Countdown'],
        'metrics' => [['Timer views', '52,600'], ['Clicks', '4,730'], ['Click rate', '9.0%'], ['Campaign revenue', '$44,820']],
        'faqs' => [
            ['Can the timer restart per visitor?', 'No. Timers use one real campaign deadline.'],
        ],
    ],

    'sticky-add-to-cart' => [
        'group' => 'convert',
        'name' => 'Sticky Add to Cart',
        'menu' => 'Keep the buy button in reach',
        'icon' => 'cursor',
        'eyebrow' => 'STICKY ATC',
        'h1' => 'Keep the buy button in reach.',
        'hero' => 'A lightweight sticky bar that appears when your add-to-cart scrolls away and brings shoppers straight back to it.',
        'seo_title' => 'Shopify Sticky Add to Cart | OrderOrbit',
        'seo_description' => 'A lightweight sticky bar that scrolls shoppers back to your theme\'s own add-to-cart button.',
        'keyword' => 'Shopify sticky add to cart',
        'problem' => ['Long product pages bury the button.', 'Shoppers scroll through images, reviews and details, then have to scroll back to buy.'],
        'steps' => ['Enable the block.', 'Choose what it shows.', 'Publish. Your theme still handles variants, quantity and cart.'],
        'grid' => ['Appears only when the original button leaves view', 'One tap returns to your theme\'s add-to-cart', 'No duplicate cart logic', 'Mobile and desktop', 'Click tracking'],
        'example' => ['title' => 'Scroll, tap, buy.', 'text' => 'The shopper scrolls into reviews, the sticky bar appears, one tap brings them back to your theme\'s own add-to-cart.', 'flow' => ['ATC leaves view', 'Sticky bar appears', 'Tap', 'Back to your ATC']],
        'templates' => ['Simple sticky bar'],
        'metrics' => [['Bar views', '27,340'], ['Clicks', '3,281'], ['Click rate', '12.0%'], ['Assisted ATC', '1,904']],
        'faqs' => [
            ['Will it conflict with my theme\'s cart?', 'No. It never adds to cart itself; it takes shoppers to your theme\'s own button.'],
        ],
    ],

    'trust-social-proof' => [
        'group' => 'convert',
        'name' => 'Trust & Social Proof',
        'menu' => 'Reviews, trust rows and guarantees',
        'icon' => 'shield',
        'eyebrow' => 'TRUST',
        'h1' => 'Show shoppers why they can trust you.',
        'hero' => 'Review cards, sliders, rating strips, trust rows and guarantee blocks, styled to your brand.',
        'seo_title' => 'Shopify Trust Badges & Social Proof | OrderOrbit',
        'seo_description' => 'Review cards, sliders, rating strips, trust rows and guarantee blocks for Shopify, styled to your brand.',
        'keyword' => 'Shopify trust badges',
        'problem' => ['New visitors don\'t know you yet.', 'Clear guarantees and real customer words answer the question before they leave.'],
        'steps' => ['Add testimonials or trust icons.', 'Pick a template.', 'Place near your buy button.', 'Publish.'],
        'grid' => ['Seven templates', 'Manual reviews and testimonials', 'Ratings and avatars', 'Trust icons and guarantee cards', 'Theme App Block placement', 'View tracking'],
        'example' => ['title' => 'Trust next to the buy button.', 'text' => 'A rating strip under the title, a trust row under add-to-cart and a guarantee card before the description.', 'flow' => ['Rating strip', 'Add to cart', 'Trust row', 'Guarantee card']],
        'templates' => ['Review Card', 'Review Slider', 'Rating Strip', 'Customer Quote', 'Avatar Testimonials', 'Trust Row', 'Guarantee Card'],
        'metrics' => [['Block views', '64,210'], ['Slider interactions', '5,380'], ['Viewers who add to cart', '11.4%'], ['Assisted revenue', '$29,760']],
        'faqs' => [
            ['Does it import from my review app?', 'Not yet; review-platform integrations are planned. You can add reviews manually today.'],
        ],
    ],

    'checkout' => [
        'group' => 'checkout',
        'name' => 'Checkout & Thank You',
        'menu' => 'Checkout, Thank You and Order Status blocks',
        'icon' => 'card',
        'eyebrow' => 'CHECKOUT EXTENSIONS',
        'h1' => 'Keep selling after the Buy button.',
        'hero' => 'Add trust, reviews, shipping progress and offers to checkout where your Shopify plan supports it — and turn Thank You and Order Status pages into your next sale.',
        'seo_title' => 'Shopify Checkout & Thank You Page Extensions | OrderOrbit',
        'seo_description' => 'Add trust, reviews, offers and cross-sells to Shopify checkout, Thank You and Order Status pages where supported.',
        'keyword' => 'Shopify checkout extensions',
        'problem' => ['Checkout is where doubt shows up.', 'Shoppers hesitate on price, delivery and trust. After they buy, the confirmation page is usually a dead end.'],
        'steps' => ['OrderOrbit checks what your store supports.', 'Pick a block.', 'Configure content and conditions.', 'Add it in Shopify\'s checkout editor and publish.'],
        'grid' => ['Review, countdown, shipping, free-gift, promotion and trust blocks', 'Thank You: review request, cross-sell, reorder, referral, survey, next-purchase discount', 'Order Status: tracking and support', 'Only shows what your plan supports', 'Block view and click tracking', 'A/B testable'],
        'note' => 'Blocks inside the checkout steps require Shopify Plus. Thank You and Order Status blocks are available on all plans that support checkout extensions.',
        'example' => ['title' => 'From doubt to the next order.', 'text' => 'A trust row and shipping progress in checkout, then a cross-sell and next-purchase discount on the Thank You page.', 'flow' => ['Checkout: trust row', 'Shipping progress', 'Purchase', 'Thank You cross-sell']],
        'templates' => ['Review Slider', 'Countdown', 'Shipping Progress', 'Free Gift', 'Promotion', 'Trust Row'],
        'metrics' => [['Block views', '15,880'], ['Block clicks', '1,207'], ['Thank You offer accepts', '612'], ['Post-purchase revenue', '$18,340']],
        'faqs' => [
            ['Can I change the checkout layout?', 'No. We add supported blocks; Shopify controls the checkout itself.'],
            ['Do I need Shopify Plus?', 'Only for in-checkout blocks.'],
        ],
    ],

    'customer-accounts' => [
        'group' => 'checkout',
        'name' => 'Customer Accounts',
        'menu' => 'Reorder, rewards and reviews in accounts',
        'icon' => 'user',
        'eyebrow' => 'CUSTOMER ACCOUNTS',
        'h1' => 'Turn customer accounts into repeat sales.',
        'hero' => 'Add reorder, rewards, reviews, product and support blocks inside Shopify customer accounts.',
        'seo_title' => 'Shopify Customer Account Extensions | OrderOrbit',
        'seo_description' => 'Reorder, rewards, reviews and support blocks inside Shopify customer accounts.',
        'keyword' => 'Shopify customer account extensions',
        'problem' => ['The account page is where loyal customers go.', 'Most stores give them an order list and nothing else.'],
        'steps' => ['Enable the blocks you want.', 'Customise text and behaviour.', 'Publish — customers see them next time they sign in.'],
        'grid' => ['My Orders', 'Track Order', 'One-click Reorder', 'My Rewards', 'My Reviews', 'My Products', 'Support'],
        'example' => ['title' => 'Reorder in one click.', 'text' => 'A returning customer signs in, sees their last order and reorders it without searching the store.', 'flow' => ['Sign in', 'My Orders', 'Reorder', 'Checkout']],
        'templates' => ['My Orders', 'Track Order', 'Reorder', 'My Rewards', 'My Reviews', 'My Products', 'Support'],
        'metrics' => [['Account visits', '9,420'], ['Reorders', '1,136'], ['Reviews submitted', '488'], ['Reorder revenue', '$41,070']],
        'faqs' => [
            ['Which customer accounts are supported?', 'Shopify\'s new customer accounts.'],
        ],
    ],

    'automation' => [
        'group' => 'grow',
        'name' => 'Lifecycle Automation',
        'menu' => 'Review, reorder and win-back workflows',
        'icon' => 'flow',
        'eyebrow' => 'AUTOMATION',
        'h1' => 'Bring customers back automatically.',
        'hero' => 'Visual workflows for review requests, welcome, VIP, reorder and win-back — triggered by real Shopify events.',
        'seo_title' => 'Shopify Lifecycle Automation | OrderOrbit',
        'seo_description' => 'Automate review requests, welcome, VIP, reorder and win-back flows for your Shopify store.',
        'keyword' => 'Shopify marketing automation',
        'problem' => ['The second order doesn\'t happen by accident.', 'Follow-ups get forgotten when they\'re manual.'],
        'steps' => ['Start from a template or blank canvas.', 'Choose a trigger.', 'Add conditions, waits and actions.', 'Test and publish.'],
        'grid' => ['10 triggers', '16 condition types', 'Email, tags, discounts, webhooks, tasks', 'Waits and if/else branches', '10 ready templates', 'Run logs with retry', 'Email sending managed for you — no SMTP'],
        'example' => ['title' => 'The review request.', 'text' => 'Order delivered → wait 5 days → email review request → if no review in 7 days → reminder.', 'flow' => ['Order delivered', 'Wait 5 days', 'Email review request', 'No review in 7 days?', 'Reminder']],
        'templates' => ['Review Request', 'Delivery Follow-up', 'New Customer Welcome', 'VIP Customer', 'Reorder Reminder', 'Win-back', 'Cross-sell', 'Product Education', 'Refund Follow-up', 'Cancellation Follow-up'],
        'metrics' => [['Workflow runs', '8,930'], ['Success rate', '99.4%'], ['Emails sent', '12,775'], ['Attributed revenue', '$22,480']],
        'faqs' => [
            ['Is this a Shopify Flow replacement?', 'No; it focuses on customer lifecycle.'],
            ['Do I need an email provider?', 'No, sending is included.'],
        ],
    ],

    'analytics' => [
        'group' => 'grow',
        'name' => 'Analytics & Attribution',
        'menu' => 'Events, funnels and revenue by experience',
        'icon' => 'chart',
        'eyebrow' => 'ANALYTICS',
        'h1' => 'Know which experiences earn revenue.',
        'hero' => 'Events, funnels, revenue by experience and customer journeys — collected through Shopify\'s consent-aware Web Pixel.',
        'seo_title' => 'Shopify Conversion Analytics & Attribution | OrderOrbit',
        'seo_description' => 'Events, funnels, revenue by experience and customer journeys from a consent-aware Shopify Web Pixel.',
        'keyword' => 'Shopify conversion analytics',
        'problem' => ['Every app claims credit.', 'Different dashboards, different numbers, no way to compare.'],
        'steps' => ['Install OrderOrbit.', 'The Web Pixel collects standard and OrderOrbit events.', 'See them in one place.'],
        'grid' => ['Event Explorer', 'Custom funnels with drop-off', 'Revenue by experience, template, variant and UTM', 'First-touch, last-touch and experience-assisted models', 'Customer journey timeline', 'Consent and retention controls'],
        'note' => 'Attribution is an analytical model, not proof of causality. Use A/B tests to prove impact.',
        'example' => ['title' => 'A bundle funnel.', 'text' => 'Product View → Bundle View → Bundle Interaction → Add to Cart → Checkout → Purchase, with drop-off at every step.', 'flow' => ['Product View', 'Bundle View', 'Interaction', 'Add to Cart', 'Checkout', 'Purchase']],
        'templates' => [],
        'metrics' => [['Events collected', '1.2M'], ['Sessions', '184,300'], ['Conversion rate', '3.1%'], ['Revenue influenced', '$212,900']],
        'faqs' => [
            ['Does it respect cookie consent?', 'Yes, through Shopify\'s Customer Privacy API.'],
        ],
    ],

    'ab-testing' => [
        'group' => 'grow',
        'name' => 'A/B Testing',
        'menu' => 'A/B and A/B/C tests with guardrails',
        'icon' => 'split',
        'eyebrow' => 'EXPERIMENTS',
        'h1' => 'Test ideas, not guesses.',
        'hero' => 'Run A/B or A/B/C tests on any experience, with traffic allocation, guardrails and results you can trust.',
        'seo_title' => 'Shopify A/B Testing for CRO | OrderOrbit',
        'seo_description' => 'Test bundles, upsells and offers with traffic allocation, guardrail metrics and clear results.',
        'keyword' => 'Shopify A/B testing',
        'problem' => ['Early results lie.', 'Calling a winner after two days is how stores ship changes that don\'t work.'],
        'steps' => ['Pick an experience.', 'Create variants.', 'Set traffic, audience and metrics.', 'Launch and watch results.'],
        'grid' => ['A/B and A/B/C', 'Traffic allocation', 'Audience targeting', 'Primary, secondary and guardrail metrics', 'Stable visitor assignment', 'Winner only after minimum duration and sample', 'One-click apply winner'],
        'example' => ['title' => 'Tier Cards vs Radio Selector.', 'text' => 'Split traffic 50/50, measure revenue per visitor, guard cart abandonment, and only call a winner after 7 days and enough visitors and conversions per variant.', 'flow' => ['50 / 50 split', 'Revenue per visitor', 'Guardrail: abandonment', '≥ 7 days + sample', 'Apply winner']],
        'templates' => [],
        'metrics' => [['Visitors per variant', '6,420'], ['Conversion A', '3.0%'], ['Conversion B', '3.6%'], ['Confidence', '96%']],
        'faqs' => [
            ['How is the winner decided?', 'Standard statistical tests at 95% confidence, after at least 7 days and a minimum sample per variant.'],
        ],
    ],

    'personalization' => [
        'group' => 'grow',
        'name' => 'Personalization',
        'menu' => 'Segments and audience rules',
        'icon' => 'target',
        'eyebrow' => 'PERSONALIZATION',
        'h1' => 'The right offer for the right shopper.',
        'hero' => 'Segments and simple rules to show different experiences to new, returning, VIP and mobile shoppers.',
        'seo_title' => 'Shopify Personalization & Segments | OrderOrbit',
        'seo_description' => 'Segments and audience rules for new, returning, VIP and mobile shoppers on Shopify.',
        'keyword' => 'Shopify personalization',
        'problem' => ['One offer rarely fits everyone.', 'A first-time visitor and a five-order customer need different nudges.'],
        'steps' => ['Pick or build a segment.', 'Create a rule.', 'Choose the experience to show.'],
        'grid' => ['Prebuilt segments', 'Custom rules', 'Device, cart value and UTM conditions', 'Segments shared across experiences, tests and workflows'],
        'example' => ['title' => 'The premium upsell.', 'text' => 'Returning + cart over $75 → premium upsell.', 'flow' => ['Returning customer', 'Cart over $75', 'Premium upsell']],
        'templates' => [],
        'metrics' => [['Segments', '8'], ['Personalized views', '21,560'], ['Segment conversion', '4.4%'], ['vs. everyone else', '+0.9 pts']],
        'faqs' => [
            ['Can I reuse a segment?', 'Yes. Segments are shared across experiences, tests and workflows.'],
        ],
    ],

];
