<?php

/*
|--------------------------------------------------------------------------
| Public feature pages
|--------------------------------------------------------------------------
|
| Copy from the Combined MVP Scope, Part E1/E2 (page copy), section 6
| (keywords) and section 11 (SEO titles). Metrics are illustrative and are
| labelled as such on the page.
|
*/

return [

    'bundles' => [
        'group' => 'convert',
        'name' => 'Bundles',
        'menu' => 'Quantity breaks, mix & match, fixed and gift bundles',
        'icon' => 'bundle',
        'eyebrow' => 'SHOPIFY BUNDLES',
        'h1' => 'Every kind of bundle, one line in the cart.',
        'hero' => 'Quantity breaks, BOGO-style offers, variant offers, mix & match, fixed packs and gift bundles. Shoppers add the whole offer in one click, it shows as one bundle line in the cart, and Shopify still deducts stock from each product.',
        'secondary_cta' => ['label' => 'Browse bundle templates', 'href' => '/templates?type=bundle'],
        'seo_title' => 'Shopify Bundle App: Quantity Breaks, Mix & Match | OrderOrbit',
        'seo_description' => 'Quantity breaks, mix & match, fixed and gift bundles for Shopify. One bundle line in the cart, inventory deducted per product, variant mapping and 16 customisable templates.',
        'keyword' => 'Shopify bundle app',
        'problem' => ['Bundles shouldn\'t fight your product page.', 'Most bundle apps sit next to your theme\'s own variant picker and add-to-cart, so shoppers add the product twice or the wrong variant. OrderOrbit bundles replace those controls where the bundle shows.'],
        'steps_heading' => 'Live in four steps.',
        'steps' => ['Choose a bundle type: quantity breaks, gifts, variant offers, mix & match or a fixed pack.', 'Pick a ready-made template and a colour preset.', 'Set your offers, products, variants, gifts and design.', 'Publish. It appears above or below your add-to-cart button automatically.'],
        'grid' => ['Six bundle types, 16 templates', 'Several offers per bundle, each with its own price and ribbon', 'Variant mapping and per-item variant pickers', 'Free gifts and add-on upsells inside the bundle', 'One bundle line in cart and checkout', 'Stock deducted from each product', 'Replaces the theme\'s variant picker and add-to-cart where it shows', 'Timer, savings summary and full design control'],
        'example' => ['title' => 'Buy more, save more.', 'text' => '1 product at $29, 2 products −10% (Most popular), 3 products −20%. The shopper picks a colour for each item, adds with one click and sees one bundle line at the bundle price.', 'flow' => ['1 product · $29', '2 products · −10% ★', '3 products · −20%', 'One bundle line in cart']],
        'templates' => ['Classic quantity breaks', '1 bought = 1 free', 'Quantity inversion offer', 'Mix & match slot cards', 'Frequently bought together', 'Fixed bundle + gifts'],
        'metrics' => [['Bundle views', '12,480'], ['Added to cart', '4,102'], ['Bundle orders', '1,318'], ['Bundle revenue', '$58,940']],
        'faqs' => [
            ['What is a template?', 'A ready-made layout to start from. After you pick one, every offer, product, text, colour, size and spacing is yours to change, with a live preview.'],
            ['Does it create extra products in my store?', 'No. The bundle uses your real products. In the cart, the items merge into one line on the main product, and orders keep each product so stock is deducted per item.'],
            ['What about my theme\'s variant picker and add-to-cart button?', 'Where a bundle shows, OrderOrbit hides your theme\'s variant picker, quantity, add-to-cart, buy-now and subscription options so they don\'t conflict. Shoppers choose variants inside the bundle.'],
            ['Can shoppers pick variants?', 'Yes. You map which variants each product offers, and shoppers choose one for each item (#1, #2 …).'],
        ],
    ],

    'progressive-gifts' => [
        'group' => 'convert',
        'name' => 'Progressive Gifts',
        'menu' => 'Free gifts, free shipping and discounts that unlock as the cart grows',
        'icon' => 'gift',
        'eyebrow' => 'PROGRESSIVE GIFTS',
        'h1' => 'Rewards that grow with the cart.',
        'hero' => 'One progress bar for everything a bigger cart earns: free gifts, a choice of gifts, free shipping and order discounts. Unlock by cart value or by number of items.',
        'secondary_cta' => ['label' => 'Browse progressive gift templates', 'href' => '/templates?type=gift'],
        'seo_title' => 'Shopify Free Gift & Free Shipping Progress Bar | OrderOrbit',
        'seo_description' => 'Progressive gifts for Shopify: free gifts, choose-your-gift, free shipping and discounts unlocked by cart value or item count, in five customisable layouts.',
        'keyword' => 'Shopify free gift and free shipping bar',
        'problem' => ['A shipping bar and a gift bar is one bar too many.', 'Shoppers need one clear answer to "what do I get if I add more?". Progressive gifts puts every reward on the same track.'],
        'steps' => ['Choose unlock by cart value or item count.', 'Add your rewards: gift, choice of gifts, free shipping or a discount.', 'Pick a layout: classic bar, minimal strip, milestone steps, reward cards or radial counter.', 'Publish. It shows under your add-to-cart button and in the cart.'],
        'grid' => ['Five layouts, each fully customisable', 'Unlock by cart value or item count', 'Free gift, choose-your-gift, free shipping, % or amount off', 'Gifts added automatically or claimed', 'Gifts removed if the cart drops below the threshold', 'Rewards applied automatically at checkout'],
        'example' => ['title' => 'Three rewards, one track.', 'text' => '$50 → free gift, $75 → free shipping, $100 → choose your gift. "Add $15.00 more to unlock free shipping!"', 'flow' => ['Cart $60', 'Free gift ✓', '$15 to free shipping', '$100 → choose your gift']],
        'templates' => ['Classic bar', 'Minimal strip', 'Milestone steps', 'Reward cards', 'Radial counter'],
        'metrics' => [['Bar views', '41,730'], ['Rewards unlocked', '6,284'], ['Gifts claimed', '3,412'], ['AOV lift', '+$14.20']],
        'faqs' => [
            ['Does it apply the free shipping and discounts?', 'Yes. Rewards apply automatically at checkout once the cart qualifies.'],
            ['What if the cart drops below a threshold?', 'The gift is taken out of the cart so nobody is charged for a "free" gift.'],
            ['Does it work in multiple currencies?', 'Thresholds convert with Shopify Markets.'],
        ],
    ],

    'cart-upsells' => [
        'group' => 'convert',
        'name' => 'Cart Upsells',
        'menu' => 'One last add-on in the cart',
        'icon' => 'sparkle',
        'eyebrow' => 'CART UPSELLS',
        'h1' => 'One last add-on, right in the cart.',
        'hero' => 'Cart recommendations with one-click add and an optional incentive that applies only to items added from the offer. (Product-page upsells live inside Bundles.)',
        'seo_title' => 'Shopify Cart Upsell App | OrderOrbit',
        'seo_description' => 'Cart upsells for Shopify with one-click add, variant choice and incentives applied at checkout.',
        'keyword' => 'Shopify cart upsell',
        'problem' => ['Pop-ups interrupt. Good upsells help.', 'Recommendations placed where shoppers are already deciding feel natural and don\'t hurt trust.'],
        'steps' => ['Choose the products to recommend.', 'Add an optional incentive.', 'Place the block in your cart.', 'Publish.'],
        'grid' => ['Carousel, grid, horizontal and minimal layouts', 'Hides products already in the cart', 'Variant choice', 'Incentive applied at checkout', 'Accept tracking', 'Never force-opens your drawer'],
        'example' => ['title' => 'The finishing touch.', 'text' => 'In the cart: "You might also like — add the travel case and save 10%".', 'flow' => ['Cart', 'Recommend travel case', 'Save 10%', 'Added']],
        'templates' => ['Carousel', 'Grid', 'Horizontal', 'Minimal Card'],
        'metrics' => [['Upsell views', '30,112'], ['Accepted', '2,409'], ['Accept rate', '8.0%'], ['Upsell revenue', '$36,150']],
        'faqs' => [
            ['Where does it show?', 'On your cart page, where you place the block in the Theme Editor.'],
            ['Where are product-page upsells?', 'Inside Bundles: add upsells to any bundle, with their own discount.'],
        ],
    ],

    'countdown-timer' => [
        'group' => 'convert',
        'name' => 'Countdown Timer',
        'menu' => 'Real deadlines for real campaigns',
        'icon' => 'clock',
        'eyebrow' => 'CAMPAIGN TIMERS',
        'h1' => 'Add real deadlines to real campaigns.',
        'hero' => 'Countdown banners and product timers tied to genuine campaign end dates.',
        'seo_title' => 'Shopify Countdown Timer | OrderOrbit',
        'seo_description' => 'Countdown banners and product timers tied to genuine campaign end dates for Shopify stores.',
        'keyword' => 'Shopify countdown timer',
        'problem' => ['Fake urgency costs trust.', 'Timers that reset on refresh are noticed. OrderOrbit timers count down to a real end date you set.'],
        'steps' => ['Set the end date and timezone.', 'Pick a template.', 'Target products or collections.', 'Publish.'],
        'grid' => ['Five templates', 'Timezone-aware', 'Product and collection targeting', 'Auto-hide or ended message', 'View and click tracking'],
        'example' => ['title' => 'A genuine sale deadline.', 'text' => '"Summer Sale ends in 02d 14h 09m".', 'flow' => ['Set end date', 'Timer counts down', 'Sale ends', 'Timer hides']],
        'templates' => ['Minimal', 'Banner', 'Premium Card', 'Offer Countdown', 'Product Countdown'],
        'metrics' => [['Timer views', '52,600'], ['Clicks', '4,730'], ['Click rate', '9.0%'], ['Campaign revenue', '$44,820']],
        'faqs' => [
            ['Can the timer restart per visitor?', 'No. Timers use one real campaign deadline.'],
        ],
    ],

    'sticky-add-to-cart' => [
        'group' => 'convert',
        'name' => 'Sticky Add to Cart',
        'menu' => 'Keep the buy button in reach',
        'icon' => 'cursor',
        'eyebrow' => 'STICKY ATC',
        'h1' => 'Keep the buy button in reach.',
        'hero' => 'A lightweight sticky bar that appears when your add-to-cart scrolls away and brings shoppers straight back to it.',
        'seo_title' => 'Shopify Sticky Add to Cart | OrderOrbit',
        'seo_description' => 'A lightweight sticky bar that scrolls shoppers back to your theme\'s own add-to-cart button.',
        'keyword' => 'Shopify sticky add to cart',
        'problem' => ['Long product pages bury the button.', 'Shoppers scroll through images, reviews and details, then have to scroll back to buy.'],
        'steps' => ['Enable the block.', 'Choose what it shows.', 'Publish. Your theme still handles variants, quantity and cart.'],
        'grid' => ['Appears only when the original button leaves view', 'One tap returns to your theme\'s add-to-cart', 'No duplicate cart logic', 'Mobile and desktop', 'Click tracking'],
        'example' => ['title' => 'Scroll, tap, buy.', 'text' => 'The shopper scrolls into reviews, the sticky bar appears, one tap brings them back to your theme\'s own add-to-cart.', 'flow' => ['ATC leaves view', 'Sticky bar appears', 'Tap', 'Back to your ATC']],
        'templates' => ['Simple sticky bar'],
        'metrics' => [['Bar views', '27,340'], ['Clicks', '3,281'], ['Click rate', '12.0%'], ['Assisted ATC', '1,904']],
        'faqs' => [
            ['Will it conflict with my theme\'s cart?', 'No. It never adds to cart itself; it takes shoppers to your theme\'s own button.'],
        ],
    ],

    'trust-social-proof' => [
        'group' => 'convert',
        'name' => 'Trust & Social Proof',
        'menu' => 'Reviews, trust rows and guarantees',
        'icon' => 'shield',
        'eyebrow' => 'TRUST',
        'h1' => 'Show shoppers why they can trust you.',
        'hero' => 'Review cards, sliders, rating strips, trust rows and guarantee blocks, styled to your brand.',
        'seo_title' => 'Shopify Trust Badges & Social Proof | OrderOrbit',
        'seo_description' => 'Review cards, sliders, rating strips, trust rows and guarantee blocks for Shopify, styled to your brand.',
        'keyword' => 'Shopify trust badges',
        'problem' => ['New visitors don\'t know you yet.', 'Clear guarantees and real customer words answer the question before they leave.'],
        'steps' => ['Add testimonials or trust icons.', 'Pick a template.', 'Place near your buy button.', 'Publish.'],
        'grid' => ['Seven templates', 'Manual reviews and testimonials', 'Ratings and avatars', 'Trust icons and guarantee cards', 'Placed in the Theme Editor', 'View tracking'],
        'example' => ['title' => 'Trust next to the buy button.', 'text' => 'A rating strip under the title, a trust row under add-to-cart and a guarantee card before the description.', 'flow' => ['Rating strip', 'Add to cart', 'Trust row', 'Guarantee card']],
        'templates' => ['Review Card', 'Review Slider', 'Rating Strip', 'Customer Quote', 'Avatar Testimonials', 'Trust Row', 'Guarantee Card'],
        'metrics' => [['Block views', '64,210'], ['Slider interactions', '5,380'], ['Viewers who add to cart', '11.4%'], ['Assisted revenue', '$29,760']],
        'faqs' => [
            ['Does it import from my review app?', 'Not yet; review-platform integrations are planned. You can add reviews manually today.'],
        ],
    ],

    'checkout' => [
        'group' => 'checkout',
        'name' => 'Checkout & Thank You',
        'menu' => 'Checkout, Thank You and Order Status blocks',
        'icon' => 'card',
        'eyebrow' => 'CHECKOUT BLOCKS',
        'h1' => 'Keep selling after the Buy button.',
        'hero' => 'Add trust, reviews, shipping progress and offers to checkout where your Shopify plan supports it — and turn Thank You and Order Status pages into your next sale.',
        'seo_title' => 'Shopify Checkout & Thank You Page Blocks | OrderOrbit',
        'seo_description' => 'Add trust, reviews, offers and cross-sells to Shopify checkout, Thank You and Order Status pages where supported.',
        'keyword' => 'Shopify checkout blocks',
        'problem' => ['Checkout is where doubt shows up.', 'Shoppers hesitate on price, delivery and trust. After they buy, the confirmation page is usually a dead end.'],
        'steps' => ['OrderOrbit checks what your store supports.', 'Pick a block.', 'Configure content and conditions.', 'Add it in Shopify\'s checkout editor and publish.'],
        'grid' => ['Review, countdown, shipping, free-gift, promotion and trust blocks', 'Thank You: review request, cross-sell, reorder, referral, survey, next-purchase discount', 'Order Status: tracking and support', 'Only shows what your plan supports', 'Block view and click tracking', 'A/B testable'],
        'note' => 'Blocks inside the checkout steps require Shopify Plus. Thank You and Order Status blocks are available on all plans that support checkout blocks.',
        'example' => ['title' => 'From doubt to the next order.', 'text' => 'A trust row and shipping progress in checkout, then a cross-sell and next-purchase discount on the Thank You page.', 'flow' => ['Checkout: trust row', 'Shipping progress', 'Purchase', 'Thank You cross-sell']],
        'templates' => ['Review Slider', 'Countdown', 'Shipping Progress', 'Free Gift', 'Promotion', 'Trust Row'],
        'metrics' => [['Block views', '15,880'], ['Block clicks', '1,207'], ['Thank You offer accepts', '612'], ['Post-purchase revenue', '$18,340']],
        'faqs' => [
            ['Can I change the checkout layout?', 'No. We add supported blocks; Shopify controls the checkout itself.'],
            ['Do I need Shopify Plus?', 'Only for in-checkout blocks.'],
        ],
    ],

    'customer-accounts' => [
        'group' => 'checkout',
        'name' => 'Customer Accounts',
        'menu' => 'Reorder, rewards and reviews in accounts',
        'icon' => 'user',
        'eyebrow' => 'CUSTOMER ACCOUNTS',
        'h1' => 'Turn customer accounts into repeat sales.',
        'hero' => 'Add reorder, rewards, reviews, product and support blocks inside Shopify customer accounts.',
        'seo_title' => 'Shopify Customer Account Extensions | OrderOrbit',
        'seo_description' => 'Reorder, rewards, reviews and support blocks inside Shopify customer accounts.',
        'keyword' => 'Shopify customer account extensions',
        'problem' => ['The account page is where loyal customers go.', 'Most stores give them an order list and nothing else.'],
        'steps' => ['Enable the blocks you want.', 'Customise text and behaviour.', 'Publish — customers see them next time they sign in.'],
        'grid' => ['My Orders', 'Track Order', 'One-click Reorder', 'My Rewards', 'My Reviews', 'My Products', 'Support'],
        'example' => ['title' => 'Reorder in one click.', 'text' => 'A returning customer signs in, sees their last order and reorders it without searching the store.', 'flow' => ['Sign in', 'My Orders', 'Reorder', 'Checkout']],
        'templates' => ['My Orders', 'Track Order', 'Reorder', 'My Rewards', 'My Reviews', 'My Products', 'Support'],
        'metrics' => [['Account visits', '9,420'], ['Reorders', '1,136'], ['Reviews submitted', '488'], ['Reorder revenue', '$41,070']],
        'faqs' => [
            ['Which customer accounts are supported?', 'Shopify\'s new customer accounts.'],
        ],
    ],

    'automation' => [
        'group' => 'grow',
        'name' => 'Lifecycle Automation',
        'menu' => 'Review, reorder and win-back workflows',
        'icon' => 'flow',
        'eyebrow' => 'AUTOMATION',
        'h1' => 'Bring customers back automatically.',
        'hero' => 'Visual workflows for review requests, welcome, VIP, reorder and win-back — triggered by real Shopify events.',
        'seo_title' => 'Shopify Lifecycle Automation | OrderOrbit',
        'seo_description' => 'Automate review requests, welcome, VIP, reorder and win-back flows for your Shopify store.',
        'keyword' => 'Shopify marketing automation',
        'problem' => ['The second order doesn\'t happen by accident.', 'Follow-ups get forgotten when they\'re manual.'],
        'steps' => ['Start from a template or blank canvas.', 'Choose a trigger.', 'Add conditions, waits and actions.', 'Test and publish.'],
        'grid' => ['10 triggers', '16 condition types', 'Email, tags, discounts, tasks', 'Waits and if/else branches', '10 ready templates', 'Run logs with retry', 'Email sending included — no email provider needed'],
        'example' => ['title' => 'The review request.', 'text' => 'Order delivered → wait 5 days → email review request → if no review in 7 days → reminder.', 'flow' => ['Order delivered', 'Wait 5 days', 'Email review request', 'No review in 7 days?', 'Reminder']],
        'templates' => ['Review Request', 'Delivery Follow-up', 'New Customer Welcome', 'VIP Customer', 'Reorder Reminder', 'Win-back', 'Cross-sell', 'Product Education', 'Refund Follow-up', 'Cancellation Follow-up'],
        'metrics' => [['Workflow runs', '8,930'], ['Success rate', '99.4%'], ['Emails sent', '12,775'], ['Attributed revenue', '$22,480']],
        'faqs' => [
            ['Is this a Shopify Flow replacement?', 'No; it focuses on customer lifecycle.'],
            ['Do I need an email provider?', 'No, sending is included.'],
        ],
    ],

    'analytics' => [
        'group' => 'grow',
        'name' => 'Analytics & Attribution',
        'menu' => 'Events, funnels and revenue by experience',
        'icon' => 'chart',
        'eyebrow' => 'ANALYTICS',
        'h1' => 'Know which experiences earn revenue.',
        'hero' => 'Events, funnels, revenue by experience and customer journeys — with consent-aware analytics.',
        'seo_title' => 'Shopify Conversion Analytics & Attribution | OrderOrbit',
        'seo_description' => 'Events, funnels, revenue by experience and customer journeys from a consent-aware Shopify Web Pixel.',
        'keyword' => 'Shopify conversion analytics',
        'problem' => ['Every app claims credit.', 'Different dashboards, different numbers, no way to compare.'],
        'steps' => ['Install OrderOrbit.', 'OrderOrbit measures views, clicks, add-to-carts and purchases.', 'See them in one place.'],
        'grid' => ['Event Explorer', 'Custom funnels with drop-off', 'Revenue by experience, template, variant and UTM', 'First-touch, last-touch and experience-assisted models', 'Customer journey timeline', 'Consent and retention controls'],
        'note' => 'Attribution is an analytical model, not proof of causality. Use A/B tests to prove impact.',
        'example' => ['title' => 'A bundle funnel.', 'text' => 'Product View → Bundle View → Bundle Interaction → Add to Cart → Checkout → Purchase, with drop-off at every step.', 'flow' => ['Product View', 'Bundle View', 'Interaction', 'Add to Cart', 'Checkout', 'Purchase']],
        'templates' => [],
        'metrics' => [['Events collected', '1.2M'], ['Sessions', '184,300'], ['Conversion rate', '3.1%'], ['Revenue influenced', '$212,900']],
        'faqs' => [
            ['Does it respect cookie consent?', 'Yes. It respects your customers\' consent choices and your store\'s privacy settings in Shopify.'],
        ],
    ],

    'ab-testing' => [
        'group' => 'grow',
        'name' => 'A/B Testing',
        'menu' => 'A/B and A/B/C tests with guardrails',
        'icon' => 'split',
        'eyebrow' => 'EXPERIMENTS',
        'h1' => 'Test ideas, not guesses.',
        'hero' => 'Run A/B or A/B/C tests on any experience, with traffic allocation, guardrails and results you can trust.',
        'seo_title' => 'Shopify A/B Testing for CRO | OrderOrbit',
        'seo_description' => 'Test bundles, upsells and offers with traffic allocation, guardrail metrics and clear results.',
        'keyword' => 'Shopify A/B testing',
        'problem' => ['Early results lie.', 'Calling a winner after two days is how stores ship changes that don\'t work.'],
        'steps' => ['Pick an experience.', 'Create variants.', 'Set traffic, audience and metrics.', 'Launch and watch results.'],
        'grid' => ['A/B and A/B/C', 'Traffic allocation', 'Audience targeting', 'Primary, secondary and guardrail metrics', 'Stable visitor assignment', 'Winner only after minimum duration and sample', 'One-click apply winner'],
        'example' => ['title' => 'Tier Cards vs Radio Selector.', 'text' => 'Split traffic 50/50, measure revenue per visitor, guard cart abandonment, and only call a winner after 7 days and enough visitors and conversions per variant.', 'flow' => ['50 / 50 split', 'Revenue per visitor', 'Guardrail: abandonment', '≥ 7 days + sample', 'Apply winner']],
        'templates' => [],
        'metrics' => [['Visitors per variant', '6,420'], ['Conversion A', '3.0%'], ['Conversion B', '3.6%'], ['Confidence', '96%']],
        'faqs' => [
            ['How is the winner decided?', 'Standard statistical tests at 95% confidence, after at least 7 days and a minimum sample per variant.'],
        ],
    ],

    'personalization' => [
        'group' => 'grow',
        'name' => 'Personalization',
        'menu' => 'Segments and audience rules',
        'icon' => 'target',
        'eyebrow' => 'PERSONALIZATION',
        'h1' => 'The right offer for the right shopper.',
        'hero' => 'Segments and simple rules to show different experiences to new, returning, VIP and mobile shoppers.',
        'seo_title' => 'Shopify Personalization & Segments | OrderOrbit',
        'seo_description' => 'Segments and audience rules for new, returning, VIP and mobile shoppers on Shopify.',
        'keyword' => 'Shopify personalization',
        'problem' => ['One offer rarely fits everyone.', 'A first-time visitor and a five-order customer need different nudges.'],
        'steps' => ['Pick or build a segment.', 'Create a rule.', 'Choose the experience to show.'],
        'grid' => ['Prebuilt segments', 'Custom rules', 'Device, cart value and UTM conditions', 'Segments shared across experiences, tests and workflows'],
        'example' => ['title' => 'The premium upsell.', 'text' => 'Returning + cart over $75 → premium upsell.', 'flow' => ['Returning customer', 'Cart over $75', 'Premium upsell']],
        'templates' => [],
        'metrics' => [['Segments', '8'], ['Personalized views', '21,560'], ['Segment conversion', '4.4%'], ['vs. everyone else', '+0.9 pts']],
        'faqs' => [
            ['Can I reuse a segment?', 'Yes. Segments are shared across experiences, tests and workflows.'],
        ],
    ],

];
