query CartTransformRunInput {
  presentmentCurrencyRate
  cart {
    lines {
      id
      quantity
      bundle: attribute(key: "_oo_bundle") {
        value
      }
      gift: attribute(key: "_oo_gift") {
        value
      }
      sellingPlanAllocation {
        sellingPlan {
          id
        }
      }
      cost {
        amountPerQuantity {
          amount
        }
      }
      merchandise {
        __typename
        ... on ProductVariant {
          id
          product {
            id
          }
        }
      }
    }
  }
  cartTransform {
    metafield(namespace: "$app", key: "bundles") {
      jsonValue
    }
  }
}
